version: 2

jobs:
  build:
    docker:
      - image: swift:5.5.0

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            apt-get -qq update
            apt-get -qq -y install lsb-release curl git libicu libxml2 libcurl4-openssl-dev libc6-dev clang
      - run:
          name: Run Tests
          command: |
            swift test
